# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
